Repository ufs-community/regional_workflow, pull requests merged in 2022-06, with the labels that each got.

#795 [Release] Fixed file path for FIXgsm
  scripts/exregional_make_ics.sh
  scripts/exregional_make_lbcs.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_SUBCONUS_Ind_3km_ics_HRRR_lbcs_RAP_suite_WoFS_v0.sh
  ush/machine/cheyenne.sh
  ush/machine/gaea.sh
  ush/machine/hera.sh
  ush/machine/jet.sh
  ush/machine/noaacloud.sh
  ush/machine/odin.sh
  ush/machine/orion.sh
  ush/machine/stampede.sh
  ush/machine/wcoss_dell_p3.sh
Labels: run_ci

#796 [develop] Update scripts to run with the latest hash of ufs weather model
  ush/config_defaults.sh
  ush/config_defaults.yaml
  ush/generate_FV3LAM_wflow.py
  ush/generate_FV3LAM_wflow.sh
  ush/setup.py
  ush/setup.sh
  ush/templates/FV3.input.yml
  ush/templates/input.nml.FV3
Labels: Tested on Hera, Tested on Orion

#779 [develop] Update MET/METplus versions and configuration files
  modulefiles/tasks/cheyenne/run_vx.local
  modulefiles/tasks/gaea/run_vx.local
  modulefiles/tasks/hera/run_vx.local
  modulefiles/tasks/wcoss_dell_p3/run_vx.local
  ush/machine/cheyenne.sh
  ush/machine/hera.sh
  ush/machine/orion.sh
  ush/machine/wcoss_dell_p3.sh
  ush/templates/parm/metplus/EnsembleStat_conus_sfc.conf
  ush/templates/parm/metplus/EnsembleStat_upper_air.conf
  ush/templates/parm/metplus/PointStat_conus_sfc.conf
  ush/templates/parm/metplus/PointStat_conus_sfc_mean.conf
  ush/templates/parm/metplus/PointStat_conus_sfc_prob.conf
  ush/templates/parm/metplus/PointStat_upper_air.conf
  ush/templates/parm/metplus/PointStat_upper_air_mean.conf
  ush/templates/parm/metplus/PointStat_upper_air_prob.conf
Labels: Tested on Hera, Tested on Cheyenne
