Repository ufs-community/regional_workflow, pull requests merged in 2022-05, with the labels that each got.

#752 Replace env with modulefiles in scripts
  tests/WE2E/run_WE2E_tests.sh
  ush/config_defaults.sh
  ush/config_defaults.yaml
  ush/launch_FV3LAM_wflow.sh
  ush/load_modules_run_task.sh
  ush/setup.py
  ush/setup.sh
Labels: high priority

#744 Standardize static data across Tier-1 platforms; fix and improve IC and LBC data retrieval
  scripts/exregional_get_extrn_mdl_files.sh
  tests/WE2E/run_WE2E_tests.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_HRRR.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_13km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_HRRR.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_HRRR_suite_RRFS_v1beta.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_HRRR.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1alpha.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_CONUScompact_3km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_community/config.grid_RRFS_SUBCONUS_3km_ics_HRRR_lbcs_RAP_suite_GFS_v15p2.sh
  tests/WE2E/test_configs/grids_extrn_mdls_suites_nco/config.nco_grid_RRFS_CONUScompact_25km_ics_HRRR_lbcs_RAP_suite_HRRR.sh
  tests/WE2E/test_configs/wflow_features/config.get_from_HPSS_ics_HRRR_lbcs_RAP.sh
  tests/WE2E/test_configs/wflow_features/config.specify_DT_ATMOS_LAYOUT_XY_BLOCKSIZE.sh
  tests/WE2E/test_configs/wflow_features/config.subhourly_post.sh
  tests/WE2E/test_configs/wflow_features/config.subhourly_post_ensemble_2mems.sh
  ush/NOMADS_get_extrn_mdl_files.sh
  ush/config_defaults.sh
  ush/machine/cheyenne.sh
  ush/machine/gaea.sh
  ush/machine/hera.sh
  ush/machine/jet.sh
  ush/machine/noaacloud.sh
  ush/machine/odin.sh
  ush/machine/orion.sh
  ush/machine/singularity.sh
  ush/machine/stampede.sh
  ush/machine/wcoss_dell_p3.sh
  ush/retrieve_data.py
  ush/set_extrn_mdl_params.sh
  ush/setup.sh
  ush/templates/data_locations.yml
Labels: ci-hera-intel-WE

#763 Add POST_OUTPUT_DOMAIN_NAME to WE2E tests for new grids
  tests/WE2E/test_configs/wflow_features/config.custom_ESGgrid.sh
  tests/WE2E/test_configs/wflow_features/config.custom_GFDLgrid.sh
  tests/WE2E/test_configs/wflow_features/config.custom_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_FALSE.sh
  tests/WE2E/test_configs/wflow_features/config.custom_GFDLgrid__GFDLgrid_USE_GFDLgrid_RES_IN_FILENAMES_eq_TRUE.sh
  ush/setup.py
Labels: bug

#771 Update sample script for NCO mode
  ush/config.nco.sh
Labels: bug

#773 removed cheyenne-specific crontab editing section
  ush/get_crontab_contents.sh
Labels: run_ci
